Array Tasks 1.0
Arens404/nowTimeForRealAtcions pull request #11
Opened 2022-08-01 16:41 UTC by Arens404

2022-08-02 10:32 UTC, Chezo requested changes

2022-08-02 10:32 UTC, Chezo commented on Sum.java
> +    public static void numbersCheck(ArrayList<Integer> numbers) {
check what on numbers? use meaningful name pls

2022-08-02 10:32 UTC, Chezo commented on Sum.java
> +    public static void numbersCheck(ArrayList<Integer> numbers) {
also use wrapper class in parameter

2022-08-02 10:32 UTC, Chezo commented on Sum.java
> +        for (int i = 0; i < numbers.stream().count(); i++) {
stream? if i accept the stream usage still wont be in for loop condition!

2022-08-02 10:32 UTC, Chezo commented on Sum.java
> +            for (int j = 0; j < numbers.stream().count(); j++) {
stream? if i accept the stream usage still wont be in for loop condition!

2022-08-02 10:32 UTC, Chezo commented on Sum.java
> +            for (int j = 0; j < numbers.stream().count(); j++) {
spoiler: numbers.size()?

2022-08-02 10:32 UTC, Chezo commented on Sum.java
> +    public static void numbersCheck(ArrayList<Integer> numbers) {
i think there's should be return a list

2022-08-02 17:19 UTC, Chezo requested changes
Theres 3 main methods! MUST BE ONE! only Main class should have main method! Only main class should have maximum 2 static method, 1 of them the main!

2022-08-02 17:19 UTC, Chezo commented on Circle.java
> +    static Scanner userInputScanner = new Scanner(System.in);
static

2022-08-02 17:19 UTC, Chezo commented on Circle.java
> +    public static double CirclePerimeter(int circleRadius){
static

2022-08-02 17:19 UTC, Chezo commented on Circle.java
> +    public static double CircleArea(int circleRadius){
static

2022-08-02 17:19 UTC, Chezo commented on ControlPanel.java
> +    static Scanner userInputScanner = new Scanner(System.in);
static

2022-08-02 17:19 UTC, Chezo commented on ControlPanel.java
> +    static Circle mainCircle = new Circle();
static

2022-08-02 17:19 UTC, Chezo commented on ControlPanel.java
> +    static Rectangle mainRectangle = new Rectangle();
static

2022-08-02 17:19 UTC, Chezo commented on ControlPanel.java
> +    public static void controlPanelForOperations(int selectInputNumber){
static

2022-08-02 17:19 UTC, Chezo commented on Main.java
> +    static Scanner userInputScanner = new Scanner(System.in);
static

2022-08-02 17:19 UTC, Chezo commented on Main.java
> +    static ControlPanel UserInputSelectOptionPanel = new ControlPanel();
static

2022-08-02 17:19 UTC, Chezo commented on Rectangle.java
> +    static Scanner userInputScanner = new Scanner(System.in);
static

2022-08-02 17:19 UTC, Chezo commented on Rectangle.java
> +    public static int RectanglePerimeter(int rectangleLateralFace, int anotherRectangleLateralFace){
static

2022-08-02 17:19 UTC, Chezo commented on Rectangle.java
> +    public static int RectangleArea(int rectangleLateralFace, int anotherRectangleLateralFace){
static

2022-08-02 17:19 UTC, Chezo commented on Rectangle.java
> +    public static double rectangleArcCoTangens(double RectangleArcCoTanegnt){
static

2022-08-02 17:19 UTC, Chezo commented on src/pinCodeTasks/pinCodeTask1.java
> +    public static void main(String[] args) {
static

2022-08-04 20:03 UTC, Chezo requested changes

2022-08-04 20:03 UTC, Chezo commented on Sum.java
> +        int[] arrayNumbers = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
should be private

2022-08-04 20:03 UTC, Chezo commented on Sum.java
> +        ArrayList<Integer> numbers = new ArrayList<Integer>();
Should be wrapper type List<Integer> numbers = new ArrayList<>();

2022-08-04 20:03 UTC, Chezo commented on Sum.java
> +    public static void numbersCheck(ArrayList<Integer> numbersOfInputArray) {
need better parameter name

2022-08-04 20:03 UTC, Chezo commented on Sum.java
> +            inputArrayNumbersSum += numbersArray[i];
too specific in this scope

2022-08-07 12:17 UTC, Chezo requested changes

2022-08-07 12:17 UTC, Chezo commented on Sum.java
> +        int[] arrayNumbers = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
should be private

2022-08-07 12:17 UTC, Chezo commented on Sum.java
> +        int[] inputNumbers = {1, 11, 22, 54, 21, 11, 78};
should be private

2022-08-09 22:02 UTC, Chezo requested changes
nothing changed expect the resolved conversation without an ansver!

2022-08-10 12:02 UTC, Arens404 commented on Sum.java
> +        int[] arrayNumbers = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
b2f08a76

2022-08-10 12:02 UTC, Arens404 commented on Sum.java
> +        int[] inputNumbers = {1, 11, 22, 54, 21, 11, 78};
b2f08a76

2022-08-10 12:02 UTC, Arens404 commented
> nothing changed expect the resolved conversation without an ansver!

b2f08a76

2022-08-15 06:41 UTC, Chezo approved these changes
acceptable

2022-08-15 06:41 UTC, merged