Circle and rectangle
Arens404/nowTimeForRealAtcions pull request #12
Opened 2022-08-01 20:10 UTC by Arens404

2022-08-02 10:28 UTC, Chezo requested changes

2022-08-02 10:28 UTC, Chezo commented on ControlPanel.java
> +    public static void controlPanelForOperations(int selectInputNumber){
still, so much static things in these classes. get rid of them!

2022-08-02 10:28 UTC, Chezo commented on ControlPanel.java
>                  double resultOfCirclePerimeter = mainCircle.CirclePerimeter(0);
why is there a magic number?

2022-08-02 10:28 UTC, Chezo commented on ControlPanel.java
>                  double resultOfCircleArea = mainCircle.CircleArea(0);
magic number again

2022-08-02 10:28 UTC, Chezo commented on ControlPanel.java
>                  int resultOfSquareArea = mainRectangle.RectangleArea(0, 0);
magic numbers

2022-08-02 10:28 UTC, Chezo commented on ControlPanel.java
>                  double resultOfRectangleDiagonal = mainRectangle.RectangleDiagonal(0, 0, " ");
magic numbers and empty string parameter?

2022-08-04 20:01 UTC, Chezo requested changes

2022-08-04 20:01 UTC, Chezo commented on Circle.java
> +        double circlePerimeter = 2*Math.PI*circleRadius;
good variable names finally

2022-08-04 20:01 UTC, Chezo commented on ControlPanel.java
> +        Rectangle mainRectangle = new Rectangle();
why we create these INSTANCES here

2022-08-04 20:01 UTC, Chezo commented on ControlPanel.java
> +                String DegreesOrRadianHelper = " ";
seems like unused variable

2022-08-04 20:01 UTC, Chezo commented on ControlPanel.java
> +                String DegreesOrRadianHelper = " ";
seems like unused variable

2022-08-04 20:01 UTC, Chezo commented on Rectangle.java
> +public class Rectangle extends Main{
why its extends main?

2022-08-04 20:01 UTC, Chezo commented on ControlPanel.java
> +public class ControlPanel extends Main{
why is extends main?

2022-08-04 20:01 UTC, Chezo commented on Circle.java
> +public class Circle extends Main{
why its extends main?

2022-08-04 20:01 UTC, Chezo commented on Rectangle.java
> +        return RectangleDiagonalOperations;
what kind of operations? its seems like its just a double which is not operation

2022-08-04 20:01 UTC, Chezo commented on Main.java
> +        } catch (NumberFormatException IllegalArgumentException){
mislead type-name pair

2022-08-04 20:01 UTC, Chezo commented on Main.java
> +        ControlPanel UserInputSelectOptionPanel = new ControlPanel();
should be private

2022-08-04 20:01 UTC, Chezo commented on Main.java
> +        Scanner userInputScanner = new Scanner(System.in);
should be private and could be final

2022-08-05 14:53 UTC, Arens404 commented on Circle.java
> +public class Circle extends Main{
because if we dont, we cant reach the scanner :(

2022-08-05 14:53 UTC, Arens404 commented on ControlPanel.java
> +public class ControlPanel extends Main{
because if we dont, we cant reach the scanner :(

2022-08-05 14:53 UTC, Arens404 commented on Rectangle.java
> +public class Rectangle extends Main{
because if we dont, we cant reach the scanner :(

2022-08-05 14:54 UTC, Arens404 commented on ControlPanel.java
> +        Rectangle mainRectangle = new Rectangle();
because we control the Rectangle methods and the circle methods here.

2022-08-07 12:15 UTC, Chezo requested changes

2022-08-07 12:15 UTC, Chezo commented on ControlPanel.java
> +        Rectangle mainRectangle = new Rectangle();
its not an answer, there no need to create an instance from the object.

2022-08-07 12:15 UTC, Chezo commented on ControlPanel.java
> +    Setter scanner = new Setter();
still have multiple scanner what are you hiding in this class, not acceptable solution, use function parameters instead!

2022-08-07 12:15 UTC, Chezo commented on Main.java
> +        ControlPanel UserInputSelectOptionPanel = new ControlPanel();
still not private, why u resolved the conversation?

2022-08-07 12:15 UTC, Chezo commented on Main.java
> +        Main main = new Main();
why we have a main instance there? big wtf...

2022-08-07 12:15 UTC, Chezo commented on Main.java
> +                    UserInputSelectOptionPanel.controlPanelForOperations(userInputNumber);
its not meaningful at all, its just too complex to be clear

2022-08-07 12:15 UTC, Chezo commented on Rectangle.java
> +    private Setter scanner = new Setter();
still multiple scanners, use function parameters instead!

2022-08-09 22:01 UTC, Chezo requested changes
eliminate the scanner specific classes and use inheritance

2022-08-10 11:43 UTC, Arens404 commented
> eliminate the scanner specific classes and use inheritance

fcd9c574

2022-08-24 11:40 UTC, merged