Pin code tasks
Arens404/nowTimeForRealAtcions pull request #13
Opened 2022-08-01 20:41 UTC by Arens404

2022-08-02 10:24 UTC, Chezo requested changes

2022-08-02 10:24 UTC, Chezo commented on src/pinCodeTasks/pinCodeTask2.java
> +            while(safeCodeCount != 77777){
magic number in while

2022-08-02 10:24 UTC, Chezo commented on src/pinCodeTasks/pinCodeTask2.java
> +                int safeGuessInput = userInputScanner.nextInt();
why is it safe? this variable name not too good

2022-08-02 10:24 UTC, Chezo commented on src/pinCodeTasks/pinCodeTask2.java
> +                int safeGuessInput = userInputScanner.nextInt();
also its not an input, its an integer.

2022-08-02 10:24 UTC, Chezo commented on src/pinCodeTasks/pinCodeTask1.java
> +        }catch (IllegalArgumentException NumberFormatException){
so which exception? illegalargument or numberformat? its mislead

2022-08-04 19:56 UTC, Chezo requested changes

2022-08-04 19:56 UTC, Chezo commented on pinCodeMainTasks.java
> +        Scanner scanner = new Scanner(System.in);
could be final and must be private

2022-08-04 19:56 UTC, Chezo commented on pinCodeMainTasks.java
> +            int UserInputContainer = scanner.nextInt();
still int

2022-08-04 19:56 UTC, Chezo commented on pinCodeMainTasks.java
> +            Scanner userInputScanner = new Scanner(System.in);
why u have multiple scanner? use function parameter instead!

2022-08-04 19:56 UTC, Chezo commented on pinCodeMainTasks.java
> +            while(pinCodeGuessCount != 5){
still magic number

2022-08-04 19:56 UTC, Chezo commented on pinCodeMainTasks.java
> +                if(pinCodeGuessCount == 5){
magic number

2022-08-04 19:56 UTC, Chezo commented on pinCodeMainTasks.java
> +                else if(pinCodeGuessCount < 5 && pinCodeGuessInput == correctPinCode){
magic number

2022-08-04 19:56 UTC, Chezo commented on pinCodeMainTasks.java
> +                else if(pinCodeGuessInput <= 999 || pinCodeGuessInput >= 9999){
magic numbers

2022-08-04 19:56 UTC, Chezo commented on pinCodeMainTasks.java
> +            Scanner userInputScanner = new Scanner(System.in);
one more scanner?

2022-08-04 19:56 UTC, Chezo commented on pinCodeMainTasks.java
> +                    else if(UserGuessInput <= 99999 || UserGuessInput >= 999999){
magic numbers

2022-08-04 19:56 UTC, Chezo commented on pinCodeMainTasks.java
> +        } catch (NumberFormatException IllegalArgumentException){
mislead name-type pair

2022-08-07 12:11 UTC, Chezo requested changes

2022-08-07 12:11 UTC, Chezo commented on pinCodeMainTasks.java
> +    private Setter scanner = new Setter();
setter or scanner? wtf?

2022-08-07 12:11 UTC, Chezo commented on pinCodeMainTasks.java
> +            int UserInputSelectionInt = pinCodeTasks.scanner.input();
wtf is this call?

2022-08-08 11:40 UTC, Arens404 commented on pinCodeMainTasks.java
> +            int UserInputSelectionInt = pinCodeTasks.scanner.input();
4a16cda1

2022-08-09 21:56 UTC, Chezo requested changes
please eliminate the extra class with scanner initialization.

2022-08-10 11:34 UTC, Arens404 commented
> please eliminate the extra class with scanner initialization.

b32293db

2022-08-13 12:41 UTC, Chezo requested changes
2 scanners, eliminate one of them

2022-08-14 11:24 UTC, Arens404 commented
> 2 scanners, eliminate one of them

c1b764f3

2022-08-15 06:33 UTC, Chezo approved these changes
acceptable

2022-08-15 06:33 UTC, merged