Oxo patterns
Arens404/nowTimeForRealAtcions pull request #14
Opened 2022-08-01 21:19 UTC by Arens404

2022-08-03 09:22 UTC, Chezo requested changes

2022-08-03 09:22 UTC, Chezo commented on oxoPattern1.java
> +                } else {
instead of 2 loops use variable set to change what to write and use 1 loop with this variable

2022-08-03 09:22 UTC, Chezo commented on oxoPattern2.java
> +
see in oxopattern1

2022-08-04 19:54 UTC, Chezo requested changes

2022-08-04 19:54 UTC, Chezo commented on oxoPattern1.java
> +            int UserInputContainer = scanner.nextInt();
just an int

2022-08-04 19:54 UTC, Chezo commented on oxoPattern1.java
> +        } catch (InputMismatchException IllegalArgumentException){
mislead name-type pair

2022-08-04 19:54 UTC, Chezo commented on oxoPattern1.java
> +        } catch (InputMismatchException IllegalArgumentException) {
mislead name-type pair

2022-08-04 19:54 UTC, Chezo commented on oxoPattern1.java
> +        } catch (InputMismatchException IllegalArgumentException) {
mislead name-type pair

2022-08-04 19:54 UTC, Chezo commented on oxoPattern1.java
> +    static Scanner userInputScanner = new Scanner(System.in);
it could be final and must be private

2022-08-05 13:48 UTC, Arens404 commented on oxoPattern1.java
> +    static Scanner userInputScanner = new Scanner(System.in);
78fa8de2

2022-08-07 12:09 UTC, Chezo requested changes

2022-08-07 12:09 UTC, Chezo commented on oxoPatternTasksMain/Setter.java
> +    }
dont really need it, why we created it?

2022-08-09 21:53 UTC, Chezo requested changes
please eliminate the extra class with scanner initialization.

2022-08-10 11:32 UTC, Arens404 commented on oxoPatternTasksMain/Setter.java
> +    }
bddedb09

2022-08-10 11:33 UTC, Arens404 commented
> please eliminate the extra class with scanner initialization.

bddedb09

2022-08-13 12:38 UTC, Chezo approved these changes

2022-08-13 12:39 UTC, merged