Map tasks2.0
Arens404/nowTimeForRealAtcions pull request #18
Opened 2022-08-16 15:54 UTC by Arens404

2022-08-22 08:01 UTC, Chezo requested changes

2022-08-22 08:01 UTC, Chezo commented on Main.java
> +        String keySelect = scanner.nextLine();
use meaningful name which is not a verb

2022-08-23 12:57 UTC, Arens404 commented on Main.java
> +        String keySelect = scanner.nextLine();
4388e443

2022-08-24 11:39 UTC, Chezo requested changes

2022-08-24 11:39 UTC, Chezo commented on Main.java
> +        System.out.println("(Press P/N)");
for what? xD

2022-08-24 12:01 UTC, Arens404 commented on Main.java
> +        System.out.println("(Press P/N)");
f8afd403

2022-08-24 16:12 UTC, Chezo requested changes

2022-08-24 16:12 UTC, Chezo commented on Main.java
> +        System.out.println("(Press P/N)");
still "     System.out.println("(Press P/N)");" FOR WHAT?

2022-08-24 16:12 UTC, Chezo commented on Main.java
> +        String keyForGetValue = scanner.nextLine();
too log name

2022-08-25 09:35 UTC, Arens404 commented on Main.java
> +        System.out.println("(Press P/N)");
5b28fa1b

2022-08-25 09:37 UTC, Arens404 commented on Main.java
> +        String keyForGetValue = scanner.nextLine();
fac30b60

2022-08-25 11:32 UTC, Chezo approved these changes

2022-08-25 11:32 UTC, merged